language: java

notifications:
 email: false

addons:
  sonarcloud:
    organization: "michelablack"
    token:
       secure: "T9ozxAL/pyGEwvih1y05SfZRZ3jhZouq3aNTr9+ZF7mjK1HP5RXM5Zlj8CXI8iSnKx2IQew+ErjBBo1qNChgb1IVFdTGg2XqSTLTinBLcaHp+zwjzs9zAhxER7qJdidJDWcd39uWsLEpcaLMsqE3XGRt87ZmKT5AA56E5k4mJmByhmvVbwHjk5zu4h0NV6BG+AyzQAei4Sp0XfAoytl6hbBdayw8KuRdSXrggoa7ZEPiF/9V2xmIWQAzdP2BhSUstMdyK++LpGIzAiLz9dy5k2CXhRC+FeH1xnAlEFz7ThilJ3apNHYgZppAX6PncxQhg6mXQSP4ssxpKRKrHQtxvr3y59hB24aexBGoG/C2tZ+sSdLChv9rhgFtnfh68Da9RYuR3nGYtfPQUYlXI3X6vApaNhMfwZsLCuXvHf3eJ93RAvZNQzQ6nb+W9wrx+lIC9Squiv+cbG+15PkqwncmXvTnUUtn+wJoqwEMvTC5T8Y1rbQsUctt1RW9alZ/7CUx3xH8gE9xGH5/IjrsEr8b995ws8HxUfWGUu+SjcfC21YEPd8YBL2/8xqcpbmkoFLAoIcBjpYXil3Bdx+drNBQfjHV9SnWUqAcazRRkSbZw3u/heISuQKfmF2Ac894v0yLxAKS6GJ3wmgZAVx7qMGlIFFg6WqlYUFW69RFeprKRHs=" 

script:  
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean test sonar:sonar -Dsonar.projectKey=michelablack_bookkeeper
