language: java
addons:
  sonarcloud:
    organization: michelablack
    token:
        secure: "4a5ce97e50ef372931a0fb8257a5668e95858e68"

  
script:
- mvn clean verify sonar:sonar -Dsonar.projectKey=michelablack_bookkeeper

